#!/bin/bash

python -m pip install .[jupyterlab] --no-deps
python -m pip install plugins/jupyterlab
python -m pip install plugins/contents
python -m pip install plugins/kernels
python -m pip install plugins/terminals
python -m pip install plugins/nbconvert
python -m pip install plugins/yjs
python -m pip install plugins/auth

jupyter serverextension enable --sys-prefix jupyter_server_proxy
