#!/bin/bash

mkdir fps && cd fps && curl -L -O https://github.com/jupyter-server/fps/archive/master.tar.gz && tar zxf master.tar.gz && cd fps-master && python -m pip install . && python -m pip install ./plugins/uvicorn && cd ../.. && rm -rf fps

python -m pip install . --no-deps
python -m pip install plugins/lab
python -m pip install plugins/jupyterlab
python -m pip install plugins/retrolab
python -m pip install plugins/contents
python -m pip install plugins/kernels
python -m pip install plugins/terminals
python -m pip install plugins/nbconvert
python -m pip install plugins/yjs
python -m pip install plugins/auth
