#!/bin/bash

python -m pip install -e plugins/lab
python -m pip install -e plugins/jupyterlab
python -m pip install -e plugins/retrolab
python -m pip install -e plugins/contents
python -m pip install -e plugins/kernels
python -m pip install -e plugins/terminals
python -m pip install -e plugins/nbconvert
python -m pip install -e plugins/yjs
python -m pip install -e plugins/auth
python -m pip install -e jupyverse_api
python -m pip install -e .
