name: test

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  types:
    name: Check types and lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: astral-sh/setup-uv@v7
        with:
          python-version: ${{ matrix.python-version }}
          activate-environment: "true"
      - name: Install jupyverse and plugins
        run: |
          uv venv --clear
          uv pip install --group test -e .
          for package in api/* plugins/*; do uv pip install -e "$package"; done
        shell: bash
      - name: Check types
        run: |
          uv run mypy ./api ./plugins
      - name: Lint
        run: |
          uv run ruff check src api notebooks plugins tests
          uv run ruff format --check src api notebooks plugins tests

  test:
    name: Run tests
    runs-on: ${{ matrix.os }}-latest
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu, macos, windows]
        python-version: [ '3.10', '3.11', '3.12', '3.13', '3.14' ]

    steps:
      - uses: actions/checkout@v6
      - uses: astral-sh/setup-uv@v7
        with:
          python-version: ${{ matrix.python-version }}
          activate-environment: "true"
      - name: Install jupyverse and plugins
        run: |
          uv venv --clear
          uv pip install --group test -e .
          for package in api/* plugins/*; do uv pip install -e "$package"; done
        shell: bash
      - name: Run tests
        run: uv run pytest -v --timeout=60 --color=yes
